version: '3'

services:

  nodejs:
    build: 
      context: ./node
    image: igorassilva/node
    container_name: nodejs
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    networks: 
      - app-network

  nginx:
    build: 
        context: ./nginx
    image: igorassilva/nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - app-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge